ASPECT_PATTERNS: tuple[tuple[str, str, float], ...] = (
    ("software", r"llama\.cpp", 3.4),
    ("software", r"lm\s+studio", 3.2),
    ("software", r"text-generation-webui", 3.1),
    ("software", r"koboldcpp", 3.1),
    ("software", r"anythingllm", 3.0),
    ("software", r"ollama", 3.0),
    ("software", r"vllm", 3.0),
    ("model", r"gpt[-\s]?oss(?:[-\s]?\d+[bB]?)?", 3.4),
    ("model", r"chatgpt", 3.3),
    ("model", r"gpt(?:[-\s]?\d+(?:\.\d+)?[a-zA-Z]?)?", 3.2),
    ("model", r"claude(?:[-\s]?\d+(?:\.\d+)?)?", 3.2),
    ("model", r"deepseek(?:[-\s]?\w+)?", 3.2),
    ("model", r"llama(?:[-\s]?\d+(?:\.\d+)?[a-zA-Z]?)?", 3.1),
    ("model", r"qwen(?:[-\s]?\d+(?:\.\d+)?[bB]?)?", 3.1),
    ("model", r"gemma(?:[-\s]?\d+(?:\.\d+)?[bB]?)?", 3.1),
    ("model", r"mistral(?:[-\s]?\w+)?", 3.1),
    ("model", r"grok(?:[-\s]?\d+(?:\.\d+)?)?", 3.0),
    ("model", r"phi(?:[-\s]?\d+(?:\.\d+)?)?", 2.9),
    ("model", r"glm(?:[-\s]?\d+(?:\.\d+)?)?", 2.9),
    ("model", r"\byi\b", 2.8),
    ("hardware", r"rtx\s*\d{4}(?:\s*ti)?", 2.8),
    ("hardware", r"\b(?:3090|4090|5070|5090)\s*(?:ti)?\b", 2.6),
    ("hardware", r"\b(?:gpu|vram|ram|cuda|rocm|nvidia|amd)\b", 2.5),
    ("hardware", r"\bm[1-4]\b", 2.3),
    ("technical", r"q\d(?:_[a-z])?(?:_[a-z])?", 2.2),
    ("technical", r"\b(?:gguf|exl2|awq|fp16|bf16)\b", 2.4),
    ("technical", r"\b(?:quantization|quantized|quantize|inference|latency|throughput|rag|embedding|prompt)\b", 2.2),
    ("technical", r"context\s+(?:length|window)", 2.3),
    ("technical", r"tokens?\s*(?:/|per)\s*sec(?:ond)?", 2.3),
    ("technical", r"\bt/s\b", 2.3),
    ("technical", r"flash\s+attention", 2.2),
    ("technical", r"\b(?:lora|qlora|fine[-\s]?tune|fine[-\s]?tuning)\b", 2.1),
)

POSITIVE_PATTERNS: tuple[tuple[str, float], ...] = (
    (r"\bless\s+hallucinat(?:e|es|ion|ions|ing)?\b", 1.6),
    (r"\bworks?\s+well\b", 1.4),
    (r"\boutperform(?:s|ed|ing)?\b", 1.4),
    (r"\b(?:good|great|excellent|amazing|impressive|useful|solid|decent)\b", 1.0),
    (r"\b(?:fast|faster|best|better|accurate|smart|smooth|cheap|efficient|stable)\b", 1.0),
    (r"\b(?:recommend|love|superior)\b", 1.0),
)

NEGATIVE_PATTERNS: tuple[tuple[str, float], ...] = (
    (r"\btoo\s+much\b", 1.5),
    (r"\bmemory\s+hog\b", 1.5),
    (r"\buses?\s+more\b", 1.1),
    (r"\bneeds?\s+more\b", 1.1),
    (r"\b(?:bad|terrible|poor|slow|slower|worse|expensive|buggy|unstable|broken)\b", 1.0),
    (r"\b(?:fail|fails|failed|failing|hallucinate|hallucinates|hallucinated|dislike)\b", 1.0),
)
