import json
import re
import os
import sys

# --- Configuration ---
# Using relative paths for better portability across different environments
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INPUT_FILE = os.path.join(BASE_DIR, "data/raw/r_LocalLlama_comments.jsonl")
OUTPUT_FILE = os.path.join(BASE_DIR, "data/processed/filtering_data.jsonl")

# Technical Keywords for Anchor Comments (Pass 1)
# Used to identify comments that directly mention relevant technical entities
ANCHOR_KEYWORDS = [
    # Models
    r"llama", r"qwen", r"gpt", r"claude", r"mistral", r"gemma", r"phi", r"yi", r"deepseek", r"grok", r"bert", r"roberta",
    # Hardware
    r"rtx", r"gpu", r"vram", r"3090", r"4090", r"nvidia", r"amd", r"cuda", r"rocm", r"tpu", r"npu", r"m1", r"m2", r"m3", r"m4",
    # Tech terms
    r"quantiz", r"gguf", r"exl2", r"awq", r"fine-tune", r"lora", r"qlora", r"inference", r"latency", r"t/s", r"token", r"context length",
    r"rag", r"embedding", r"vllm", r"ollama", r"koboldcpp", r"text-generation-webui", r"local", r"self-host"
]

# 7-Layer Schema Keywords for Technicality Score calculation
SCHEMA_KEYWORDS = {
    "model": [r"llama", r"qwen", r"gpt", r"claude", r"mistral", r"gemma", r"phi", r"yi", r"deepseek", r"grok"],
    "hardware": [r"rtx", r"gpu", r"vram", r"3090", r"4090", r"nvidia", r"amd", r"cuda", r"rocm", r"tpu", r"npu", r"ram"],
    "format": [r"gguf", r"exl2", r"awq", r"fp16", r"bf16", r"q4_k_m", r"q8_0"],
    "software": [r"ollama", r"vllm", r"kobold", r"lm studio", r"text-generation-webui", r"pytorch", r"transformers"],
    "performance": [r"t/s", r"tokens per second", r"latency", r"speed", r"fast", r"slow", r"throughput"],
    "training": [r"lora", r"qlora", r"fine-tune", r"train", r"dataset", r"epoch", r"loss"],
    "concept": [r"rag", r"agent", r"context", r"attention", r"quantization", r"embedding", r"prompt"]
}

# Regex patterns for text denoising
URL_PATTERN = re.compile(r'https?://\S+|www\.\S+')
CODE_BLOCK_PATTERN = re.compile(r'```.*?```|`.*?`', re.DOTALL)
TABLE_PATTERN = re.compile(r'\|.*\|.*\n(?:\|[-:| ]*\|.*\n)+', re.MULTILINE)
MEME_PATTERNS = [
    r"take my upvote", r"this is the way", r"underrated comment", r"came here to say this",
    r"faith in humanity restored", r"instructions unclear", r"banana for scale"
]
BOT_AUTHORS = {"AutoModerator", "RemindMeBot", "CommonMisspellingBot", "WikiSummarizerBot"}

def clean_text(text):
    """
    Performs surgical denoising of Reddit text while preserving technical markers.
    """
    if not text: return ""
    # Remove code blocks and tables to reduce noise
    text = CODE_BLOCK_PATTERN.sub('', text)
    text = TABLE_PATTERN.sub('', text)
    # Remove URLs
    text = URL_PATTERN.sub('', text)
    # Convert Markdown links to plain text: [text](url) -> text
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text)
    # Remove common Reddit memes
    for meme in MEME_PATTERNS:
        text = re.sub(rf"(?i)\b{meme}\b", "", text)
    # Standardize whitespace
    text = " ".join(text.split())
    return text

def is_deleted(data):
    """
    Checks if a comment is deleted, removed, or generated by a known bot.
    """
    body = data.get("body", "")
    author = data.get("author", "")
    return body in {"[deleted]", "[removed]"} or author in BOT_AUTHORS or author.endswith("Bot")

def get_technicality_score(text_lower):
    """
    Calculates technicality score based on the 7-layer schema coverage.
    """
    score = 0
    for category, keywords in SCHEMA_KEYWORDS.items():
        found = sum(1 for k in keywords if re.search(rf"\b{re.escape(k)}\b", text_lower))
        if found > 0:
            score += 1 # Count distinct technical layers present
    return score

def main():
    print(f"Initializing Industrial Filter for {INPUT_FILE}...")
    
    anchor_ids = set()
    total_lines = 0
    
    # Pass 1: Identification of Explicit Technical Entities
    print(f"Pass 1: Identifying Anchor Comments...")
    anchor_regex = re.compile(rf"(?i)\b({'|'.join(ANCHOR_KEYWORDS)})\b")
    
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Input file {INPUT_FILE} not found.")
        return

    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        for line in f:
            total_lines += 1
            try:
                data = json.loads(line)
            except: continue
            
            if is_deleted(data): continue
            
            body = data.get("body", "").lower()
            if anchor_regex.search(body):
                anchor_ids.add(data.get("id"))
            
            if total_lines % 100000 == 0:
                print(f"   Scanned {total_lines:,} lines... Found {len(anchor_ids):,} anchors.")

    print(f"Pass 1 Complete. Found {len(anchor_ids):,} anchor comments.")

    # Pass 2: Ancestry-Aware Filtering and Quality Control
    print(f"Pass 2: Processing and Denoising...")
    saved_count = 0
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    with open(INPUT_FILE, 'r', encoding='utf-8') as f_in, \
         open(OUTPUT_FILE, 'w', encoding='utf-8') as f_out:
        
        for idx, line in enumerate(f_in):
            try:
                data = json.loads(line)
            except: continue
            
            comment_id = data.get("id")
            parent_id = data.get("parent_id", "")
            # reddit parent_id format is t1_ID or t3_ID.
            clean_parent_id = parent_id.split('_')[-1] if '_' in parent_id else parent_id
            
            # Implementation of Ancestry-Aware Logic
            is_anchor = comment_id in anchor_ids
            is_child_of_anchor = clean_parent_id in anchor_ids
            
            if not (is_anchor or is_child_of_anchor):
                continue
                
            if is_deleted(data): continue
            
            # Cleaning and quality thresholds
            raw_body = data.get("body", "")
            cleaned_body = clean_text(raw_body)
            words = cleaned_body.split()
            word_count = len(words)
            
            # Goldilocks Zone for word count (10 to 80 words)
            if not (10 <= word_count <= 80):
                continue
                
            text_lower = cleaned_body.lower()
            tech_score = get_technicality_score(text_lower)
            
            # Ensure technical relevance
            if tech_score == 0 and not is_child_of_anchor:
                continue
                
            data_elite = {
                "id": comment_id,
                "parent_id": parent_id,
                "body": cleaned_body,
                "word_count": word_count,
                "technicality_score": tech_score,
                "is_anchor": is_anchor,
                "score": data.get("score", 0),
                "created_utc": data.get("created_utc"),
                "permalink": data.get("permalink")
            }
            
            f_out.write(json.dumps(data_elite) + '\n')
            saved_count += 1
            
            if (idx + 1) % 100000 == 0:
                print(f"   Processed {idx+1:,} lines... Saved {saved_count:,} elite comments.")

    print(f"\nSTATISTICAL SUMMARY")
    print(f"----------------------")
    print(f"Total Lines Processed: {total_lines:,}")
    print(f"Anchor Comments:       {len(anchor_ids):,}")
    print(f"Total Elite Saved:     {saved_count:,}")
    print(f"Retention Rate:        {(saved_count/total_lines)*100:.2f}%")
    print(f"Output Path:           {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
